### ISSUE TITLE
Links to other parts of the same repo should be realtive

### ISSUE THREAD

**Issue by ilevantis** [symbiolab/bio-labware#5]
Currently all links to other documents in the repo and all links to headings in the same file are absolute.
e.g. `[Spectroscopy](https://github.com/symbiolab/bio-labware/blob/master/030_spectroscopy.md)`

This causes issues when forking or working on different branches and should be changed to relative paths.

See formatting help here:
https://github.com/blog/1395-relative-links-in-markup-files

**Comment by bostjanvihar** [comment]
I see, thanks for the info!

**Comment by bostjanvihar** [comment]
Done =)
